env:
  global:
    - ACTIVE_ENV=development.test

language: java

services:
  - mysql

before_install:
  - cp src/main/resources/database.properties.ci src/main/resources/database.properties 
  - mvn db-migrator:create
  - mvn db-migrator:migrate
  - chmod +x ./utils/travis-db-setup.sh ; ./utils/travis-db-setup.sh

script:
  - mvn test
  
